### ISSUE TITLE
PKGBUILD

### ISSUE THREAD

**Issue by toddejohnson** [jdorel/systemd-metered-connection-dependency#3]
I found this looking for a way to prevent restic backups on mobile. I'm writing a PKGBUILD and thinking to contribute it to AUR. Would you like it in this repo too? I have to admit it would be my first AUR.

**Comment by jdorel** [comment]
It think it would be great.

**Comment by toddejohnson** [comment]
I've got a start based upon master. Would you be willing to tag a release so the package is versioned?

**Comment by jdorel** [comment]
Done

**Comment by toddejohnson** [comment]
One down(I already had it I'm not letting it go to waste.)

https://aur.archlinux.org/packages/systemd-metered-connection-dependency-git

**Comment by toddejohnson** [comment]
... and now the release version. 

https://aur.archlinux.org/packages/systemd-metered-connection-dependency/

If this works feel free to close this issue. I'd love to add you as a maintainer if you are interested.

**Comment by jdorel** [comment]
Thanks, it works for me.

For the maintaining of the AUR package, I am not yet familiar with the creation of PKGBUILD (although it's on my todo list). Feel free to add me as a maintainer, but I cannot guarantee I would update the PKGBUILD for new versions for now.

**Comment by toddejohnson** [comment]
Eh mostly once it is setup bumping the version and pushing is most of it unless there is a huge change.

**Comment by HaleTom** [comment]
@jdorel  would you consider updating the README TODO removing this and and adding Arch install instructions?
